config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :photographers do
    resources :bookings, only: [:create, :destroy]
  end

  resources :bookings, only: [:index, :show]

  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :photographer
  validates :hours, presence: true
  validates :date, presence: true
  validates :location, presence: true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :photographer
  mount_uploader :photo, PhotoUploader
end

app/models/photographer.rb
class Photographer < ApplicationRecord
  include PgSearch
  pg_search_scope :global_search,
    against: [ :description, :category, :city ],
    associated_against: {
      user: [ :first_name, :last_name ]
    },
    using: {
      tsearch: { prefix: true }
    }

  belongs_to :user
  has_many :bookings
  has_many :photos, dependent: :destroy
  mount_uploader :avatar, PhotoUploader
  validates :description, presence: true
  validates :city, presence: true
  validates :hourly_rate, presence: true
  validates :category, presence: true, inclusion: { in: [ "Weddings", "Birthdays", "Graduation", "Fashion", "Portraits", "Maternity", "Pets"] }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :bookings
  has_many :photographers, through: :bookings
  validates :first_name, presence: true
  validates :last_name, presence: true

  def is_photographer?
    if Photographer.where(user_id: self.id).any?
      return true
    else
      false
    end
  end

  def photographer_id
    Photographer.where(user_id: self.id).first.id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :store_user_location!, if: :storable_location?
  before_action :authenticate_user!
  include Pundit
  before_action :configure_permitted_parameters, if: :devise_controller?
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    store_location_for(:user, request.fullpath)
  end

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :destroy]

  def index
    @bookings = policy_scope(Booking)
  end

  def show
  end

  def create
    @booking = Booking.new(booking_params)
    @photographer = Photographer.find(params[:photographer_id])
    @booking.photographer = @photographer
    @booking.user = current_user
    authorize @booking
    if @booking.save
      redirect_to booking_path(@booking)
    else
      render 'photographers/show'
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def set_booking
    @booking = Booking.find(params[:id])
    authorize @booking
  end

  def booking_params
    params.require(:booking).permit(:date, :hours, :location)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/photographers_controller.rb
class PhotographersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_photographer, only: [:show, :edit, :update, :destroy]

  def index
    @photographers = policy_scope(Photographer)
    if params[:search].present?
      @photographers = Photographer.global_search(params[:search]).order("created_at DESC")
    else
      @photographers = Photographer.all.order("created_at DESC")
    end
  end

  def show
    @booking = Booking.new
  end

  def new
    redirect_to bookings_path if current_user.is_photographer?
    @user = current_user
    @photographer = Photographer.new
    @photos = @photographer.photos.build
    authorize @photographer
  end

  def create
    @photographer = Photographer.new(photographer_params)
    @photographer.user = current_user
    authorize @photographer
    respond_to do |format|
      if @photographer.save
        params[:photos]['photo'].each do |a|
        @photos = @photographer.photos.create!(:photo => a, :photographer_id => @photographer.id)
      end
        format.html { redirect_to @photographer, notice: 'Photo was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    if params[:photos]
      @photographer.photos.destroy_all
      params[:photos]['photo'].each do |a|
        @photos = @photographer.photos.create!(:photo => a, :photographer_id => @photographer.id)
        @photographer.save
      end
    end
    @photographer.update(photographer_params)
    redirect_to photographer_path(@photographer)
  end

  def destroy
    @photographer.destroy
    redirect_to bookings_path
  end

  private

  def set_photographer
    @photographer = Photographer.find(params[:id])
    authorize @photographer
  end

  def photographer_params
    params.require(:photographer).permit(:description, :category, :city, :hourly_rate, :avatar, :avatar_cache, :search)
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
before_action :set_photo, only: [:show, :edit, :update, :destroy]

 # GET /photos
 # GET /photos.json
 def index
   @photos = Photo.all
 end

 # GET /photos/1
 # GET /photos/1.json
 def show
 end

 # GET /photos/new
 def new
   @photo = Photo.new
 end

 # GET /photos/1/edit
 def edit
 end

 # POST /photos
 # POST /photos.json
 def create
   @photo = Photo.new(photo_params)

   respond_to do |format|
     if @photo.save
       format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
       format.json { render :show, status: :created, location: @photo }
     else
       format.html { render :new }
       format.json { render json: @photo.errors, status: :unprocessable_entity }
     end
   end
 end

 # PATCH/PUT /photos/1
 # PATCH/PUT /photos/1.json
 def update
   respond_to do |format|
     if @photo.update(photo_params)
       format.html { redirect_to @photo.post, notice: 'Photo was successfully updated.' }
       format.json { render :show, status: :ok, location: @photo }
     else
       format.html { render :edit }
       format.json { render json: @photo.errors, status: :unprocessable_entity }
     end
   end
 end

 # DELETE /photos/1
 # DELETE /photos/1.json
 def destroy
   @photo.destroy
   respond_to do |format|
     format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
     format.json { head :no_content }
   end
 end

 private
   # Use callbacks to share common setup or constraints between actions.
   def set_photo
     @photo = Photo.find(params[:id])
   end

   # Never trust parameters from the scary internet, only allow the white list through.
   def photo_params
     params.require(:photos).permit(:photo)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h2 class="spacing text-center">BOOKINGS</h2>
<ul class="inbox">
  <% count = 0 %>
  <% @bookings.each do |booking| %>
    <% if booking.user == current_user %>
      <li class="message">
        <%= cl_image_tag booking.photographer.avatar, height: 100, width: 100, crop: :thumb, class: "message-avatar" %>
        <div class="message-name">
          <h4><%= link_to booking.photographer.user.first_name, photographer_path(booking.photographer) %></h4>
          <p class="light-text"><%= booking.photographer.user.email %></p>
        </div>
        <div class ="message-body">
          <p><strong>Location:</strong> <%= booking.location.capitalize %></p>
          <p><strong>Date:</strong> <%= booking.date %></p>
          <p><strong>Number of hours:</strong> <%= booking.hours %></p>
          <p><strong>Total booking fee:</strong> £<%= booking.photographer.hourly_rate * booking.hours %></p>
        </div>
        <div class ="message-status">
          <p class="status-pending"><%= link_to "x", photographer_booking_path(photographer_id: booking.photographer.id, id: booking.id), method: :delete, id: 'btn-blue' %><p>
          <% count += 1 %>
    <% end %>
  <% end %>
  <% if count == 0 %>
    <div>
      <p class="no-booking text-center"> You have no bookings.. <%= link_to "book",photographers_path %> an amazing photographer for your event!</p>
    </div>
  <% end %>
  </div>
  </li>
</ul>


<h2 class="spacing text-center">JOBS</h2>
<ul class="inbox">
 <% count = 0 %>
 <% @bookings.each do |booking| %>
 <% if booking.photographer.user == current_user %>
 <li class="message">
  <div class="message-name">
    <h4><%= booking.user.first_name %></h4>
    <p class="light-text"><%= booking.user.email %></p>
  </div>
  <div class ="message-body">
    <p><strong>Booking Location:</strong> <%= booking.location.capitalize %></p>
    <p><strong>Date:</strong> <%= booking.date %></p>
    <p><strong>Number of hours:</strong> <%= booking.hours %></p>
    <p><strong>Total booking fee:</strong> £<%= booking.photographer.hourly_rate * booking.hours %></p>
    <!-- <p class="light-text"><%= booking.photographer.description %></p> -->
  </div>
  <div class ="message-status">
    <p class="status-pending"><%= link_to "x", photographer_booking_path(photographer_id: booking.photographer.id, id: booking.id), method: :delete, id: 'btn-blue' %><p>
      <% count += 1 %>
      <% end %>
      <% end %>
      <% if count == 0 %>
      <div>
        <p class="no-booking text-center">You have no jobs..
          <% if current_user.is_photographer? %>
            <%= link_to "update", photographer_path(current_user.photographer_id) %> your photographer profile and start earning today!</p>
          <% else %>
            <%= link_to "become", new_photographer_path %> a photographer and start earning today!</p>
          <% end %>
      </div>
     <% end %>
   </div>
 </li>
</ul>

app/views/bookings/show.html.erb
<div class="confirmation-page-container">
  <div class="text-center">
    <h1 id="confirmation-header">You've Snapped Up A Good One!</h1>
    <div class="confirmation-container">
      <h3>Great news, you have a booking with <%= @booking.photographer.user.first_name.capitalize %>.</h2>
      <%= cl_image_tag @booking.photographer.avatar, height: 100, width: 100, crop: :thumb, class: "confirmation-avatar" %>
      <div class="order-details">
        <h4><strong>Date:</strong> <%= @booking.date %></h4>
        <h4><strong>Location:</strong> <%= @booking.location.capitalize %></h4>
        <h4><strong>Booking total:</strong> £<%= @booking.photographer.hourly_rate * @booking.hours %></h4>
      </div>
    </div>
    <div class="confirmation-btn">
      <%= link_to "Make another booking", photographers_path, id: "btn-blue" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Oh Snap! | Book / Become a Photographer</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,500,700,900" rel="stylesheet">
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%#= render 'shared/flashes' %>
      <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner">
  <div class="banner-text">
    <h2><strong><%= link_to "BOOK", photographers_path %> / <%= link_to "BECOME", new_photographer_path %></strong></h2>
    <h2><strong>A PHOTOGRAPHER</strong></h2>
  </div>
</div>

<div class="box-orange">
</div>

<div class="home-box" id="home-box">
  <h1>HOW IT WORKS</h1>
  <div class="how-box">
    <div class="how-text">
      <h3>Tell us when, where and why. We take care of the rest.</h3>
      <p>The more we know, the better we can help out. In addition to the basic logistics like location and time, let us know the style and feel you're looking for.</p>
    </div>
    <div class="how-image">
      <%= cl_image_tag("screen_shot", width:600, height: 400) %>
    </div>
  </div>
</div>

<div class="box-blue">
</div>

<div class="people" id="people">
  <h1>MEET THE TEAM</h1>
  <div class="people-box">

    <div class="people-card">
      <div class="team-avatar">
        <%= cl_image_tag("kat", width: 100, height: 100, crop: :thumb, gravity: :face) %>
        <div class="overlay">
          <%= cl_image_tag("cat", width: 100, height: 100, crop: :thumb, gravity: :face) %>
        </div>
      </div>
      <div class="people-info">
        <h3>Kat</h3>
        <p>CEO</p>
        <p class="people-description">Cat Enthusiast</p>
      </div>
    </div>

    <div class="people-card">
      <div class="team-avatar">
        <%= cl_image_tag("shirley", width: 100, height: 100, crop: :thumb, gravity: :face) %>
        <div class="overlay">
          <%= cl_image_tag("chocolate", width: 100, height: 100, crop: :thumb, gravity: :face) %>
        </div>
      </div>
      <div class="people-info">
        <h3>Shirley</h3>
        <p>Senior Developer</p>
        <p class="people-description">Chocaholic</p>
      </div>
    </div>

    <div class="people-card">
      <div class="team-avatar">
        <%= cl_image_tag("amina", width: 100, height: 100, crop: :thumb, gravity: :face) %>
        <div class="overlay">
          <%= cl_image_tag("kebab", width: 100, height: 100, crop: :thumb, gravity: :face) %>
        </div>
      </div>
      <div class="people-info">
        <h3>Amina</h3>
        <p>Developer</p>
        <p class="people-description">Kebab Konnoisseur</p>
      </div>
    </div>

    <div class="people-card">
      <div class="team-avatar">
        <%= cl_image_tag("alisa", width: 100, height: 100, crop: :thumb, gravity: :face) %>
        <div class="overlay">
          <%= cl_image_tag("potato", width: 100, height: 100, crop: :thumb, gravity: :face) %>
        </div>
      </div>
      <div class="people-info">
        <h3>Alisa</h3>
        <p>Head of Design</p>
        <p class="people-description">Potato Lover</p>
      </div>
    </div>
  </div>
</div>

app/views/photographers/index.html.erb
<div class="search">
  <h1><strong>TAKE YOUR PIC</strong></h1>
  <%= form_tag photographers_path, method: :get, id: "search-form" do %>
    <%= text_field_tag :search, params[:search], options = {style:"text-align: center;height:30px;width:250px;border-radius:4px;", placeholder: "Search by name or keyword"} %>
    <%= submit_tag "Search", class: "search-btn" %>
  <% end %>
</div>

<% if @photographers.blank? %>
  <div class="search-error text-center">
    <h4>ISO sorry, there are no photographers who match your search (<%= params[:search] %>).</h4>
    <h4>Please try again.</h4>
  </div>

<% else  %>

  <div class="container fill-high">
    <div class="row">
      <% @photographers.each do |photographer| %>
        <div class="col-xs-12 col-sm-6 col-md-4 col-lg-3">
          <div class="search-results-card">
            <%= cl_image_tag (photographer.photos.exists? ? photographer.photos.first.photo : 'https://cdn.cnn.com/cnnnext/dam/assets/120306151541-flights-cheese-super-169.jpg'), height: 100, width: 200, crop: :fill, class: "search-gallery"%>
              <div class="search-information">
                <%= cl_image_tag photographer.avatar, height: 50, width: 50, crop: :thumb, gravity: :face, class: "search-avatar" %>
                <h3><%= photographer.user.first_name %> <%= photographer.user.last_name %></h3>
                <p><%= photographer.city.capitalize %></p>
                <p><%= cl_image_tag photographer.category %></p>
                <p>£<%= photographer.hourly_rate %>/Hour</p>
                <% rand(3..5).times do %>
                  <%= cl_image_tag("star") %>
                <% end %>
              </div>
              <%= link_to "+", photographer_path(photographer), class: "card-link" %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/photographers/new.html.erb
<div class="container form-container white">
  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <h2 class="spacing blue-font text-center">CREATE YOUR PROFILE</h2>
      <%= render 'shared/form' %>
    </div>
  </div>
</div>

app/views/photographers/show.html.erb
<div class="photographer-prof">
  <div class="photographer-prof-title">
    <h1>LET'S CLICK</h1>
  </div>

  <div class="photographer-photos">
    <% @photographer.photos.each do |photo| %>
      <%= cl_image_tag photo.photo, height: 200, width: 200, crop: :fill, radius: 1 %>
    <% end %>
  </div>

  <div class="photographer-info-container text-center">
    <div class="photographer-bio">
      <%= link_to photographers_path do %>
        <div class="back-arrow"><i class="fas fa-angle-double-left"></i></div>
      <% end %>

      <div class="photographer-name">
        <h3>
          <%= @photographer.user.first_name.upcase%> <%=@photographer.user.last_name.upcase%>
          <span class="photographer-edit">
            <% if @photographer.user == current_user %>
              <a href data-toggle="modal" data-target="#myModal" id="edit"><i class="fas fa-pencil-alt"></i></a>
              <%= link_to photographer_path, method: :delete do %>
                <i class="fas fa-trash"></i>
              <% end %>
            <% end %>
          </span>
        </h3>
      </div>

      <div class="photographer-avatar">
        <%= cl_image_tag @photographer.avatar, height: 100, width: 100, crop: :thumb, gravity: :face %>
      </div>

      <div class="photographer-information text-center">
        <p><%=@photographer.description%></p>
        <p><strong>Location: </strong><%= @photographer.city %></p>
        <p><strong>Hourly rate: </strong>£<%= @photographer.hourly_rate %></p>
        <p><%= cl_image_tag(@photographer.category) %></p>
        <p><% rand(3..5).times do %>
          <%= cl_image_tag("star") %>
        <% end %></p>
      </div>
    </div>

    <div class= "booking-form">
      <h3>BOOK ME</h3>
        <%= simple_form_for [@photographer, @booking] do |f| %>
        <p>Date and time:</p>
        <%= f.input :date,label: false %>
        <p>Number of hours:</p>
        <%= f.input :hours, label: false %>
        <p>Location:</p>
        <%= f.input :location,label:false %>
        <%= f.submit class: "btn-orange" %>
      <% end %>
    </div>

  </div>
</div>
<div class="modal fade" id="myModal" role="dialog">
  <div class="modal-dialog modal-md">
    <div class="modal-content">
      <div class="modal-header text-center">
        <button type="button" class="close" data-dismiss="modal"><i class="fas fa-times"></i></button>
        <h2 class="form-title spacing blue-font text-center">EDIT YOUR PROFILE</h2>
      </div>
      <div class="modal-body text-center">
        <div class="">
          <%= render 'shared/form' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer-distributed">

  <div class="footer-left">

    <h3>OH SNAP!</h3>

    <div class="footer-links">
     <%= link_to "Home", root_path %>
     ·
     <%= link_to "About", root_path + "#home-box" %>
     ·
     <%= link_to "Team", root_path + "#people" %>
     ·
     <%= link_to "Dashboard", bookings_path %>
    </div>

    <p class="footer-company-name">Oh snap! &copy; 2018</p>
  </div>

  <div class="footer-center">

    <div>
      <i class="fa fa-map-marker"></i>
      <p><span>Unit 13, 138 Kingsland Rd, London E2 8DY</span> London, UK</p>
    </div>

    <div>
      <i class="fa fa-phone"></i>
      <p>+44 (0) 2078 123456</p>
    </div>

    <div>
      <i class="fa fa-envelope"></i>
      <p>info@ohsnap.com</p>
    </div>

  </div>

  <div class="footer-right">

    <p class="footer-company-about">
      <span>ABOUT US</span>
      Oh snap! is a revolutionary marketplace that allows you to instantly book a quality photographer and earn money by listing your photography skills.
    </p>

    <div class="footer-icons">

      <a href="#"><i class="fab fa-facebook"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
      <a href="#"><i class="fab fa-linkedin"></i></a>
      <a href="#"><i class="fab fa-github"></i></a>

    </div>

  </div>

</footer>

app/views/shared/_form.html.erb
<%= simple_form_for(@photographer) do |f| %>
  <label id="btn-blue">
    + Profile Photo
    <span style="display: none">
    <%= f.input :avatar %>
    <%= f.input :avatar_cache, as: :hidden %>
    </span>
  </label>
  <%= f.input :description, label: false, placeholder: 'Describe your experience' %>
  <%= f.input :category, label: false, prompt: "Category", collection: [ "Weddings", "Birthdays", "Graduation", "Portraits", "Maternity", "Pets", "Fashion"] %>
  <%= f.input :city, label: false, placeholder: 'Your city' %>
  <%= f.input :hourly_rate, label: false, placeholder: 'Hourly rate' %>
  <label id="btn-blue">
    + Up to 5 Portfolio Images
    <span style="display: none">
      <%= f.fields_for :photos do |p| %>
        <%= f.file_field :photo, label: "Images", multiple: true, name: "photos[photo][]" %>
      <% end %>
    </span>
  </label>
  <label id="btn-blue">
    Submit
    <span style="display: none">
    <%= f.submit %>
    </span>
  </label>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-snap">
  <div class="navbar-name">
    <% if user_signed_in? %>
      <% if current_user.is_photographer? %>
        <div id="navbar-hello">Hello <%= link_to current_user.first_name.capitalize, photographer_path(current_user.photographer_id), id: "navbar-hello" %>!</div>
      <% else %>
        <div id="navbar-hello">Hello <%= current_user.first_name.capitalize %>!</div>
      <% end %>
    <% end %>
  </div>

<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to "OH SNAP!", root_path, id: "navbar-logo" %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <!-- Links when logged in -->
      <% a = [] %>
      <% Photographer.all.each do |photographer| %>
        <% if photographer.user == current_user %>
          <% a << photographer %>
        <% end %>
      <% end %>
      <% if a.empty? %>
        <%= link_to "Become a Photographer", new_photographer_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
      <%= link_to "My Dashboard", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to destroy_user_session_path, class: "navbar-wagon-item navbar-wagon-link", method: :delete do %>
        <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log Out") %>
      <% end %>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <% if user_signed_in? %>
      <!-- Links when logged in -->
          <% a = [] %>
          <% Photographer.all.each do |photographer| %>
            <% if photographer.user == current_user %>
              <% a << photographer %>
            <% end %>
          <% end %>
          <% if a.empty? %>
            <li><%= link_to "Become a Photographer", new_photographer_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <% end %>
          <li><%= link_to "My Dashboard", bookings_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
          <li><%= link_to destroy_user_session_path, method: :delete do %>
            <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log Out") %>
          <% end %></li>
        <% else %>
          <!-- Login link (when logged out) -->
          <li><%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
</div>